Search.appendIndex(
    [
                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient",
            "name": "ANAFAPIClient",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method___construct"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ACheckTVAStatus\u0028\u0029",
            "name": "CheckTVAStatus",
            "summary": "Check\u0020if\u0020a\u0020company\u0020is\u0020registered\u0020for\u0020TVA",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_CheckTVAStatus"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AGetEntity\u0028\u0029",
            "name": "GetEntity",
            "summary": "Get\u0020company\/institution\u0020data\u0020from\u0020ANAF",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_GetEntity"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ASanitizeCUI\u0028\u0029",
            "name": "SanitizeCUI",
            "summary": "Sanitize\u0020CUI\u0020input\u0020for\u0020most\u0020requests.",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_SanitizeCUI"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AGetLoginURL\u0028\u0029",
            "name": "GetLoginURL",
            "summary": "Helper\u0020method\u0020for\u0020the\u0020initial\u0020OAuth2\u0020login",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_GetLoginURL"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AProcessOAuthCallback\u0028\u0029",
            "name": "ProcessOAuthCallback",
            "summary": "Gets\u0020the\u0020access\u0020token\u0020from\u0020ANAF,\u0020should\u0020be\u0020called\u0020from\u0020the\u0020OAuth\u0020callback\u0020script",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_ProcessOAuthCallback"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AGetAccessToken\u0028\u0029",
            "name": "GetAccessToken",
            "summary": "Gets\u0020the\u0020current\u0020access\u0020token\u0020\u0028if\u0020it\u0020exists\u0029,\u0020tries\u0020to\u0020load\u0020it\u0020from\u0020the\u0020file\u0020if\u0020necessary",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_GetAccessToken"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ASaveAccessToken\u0028\u0029",
            "name": "SaveAccessToken",
            "summary": "Saves\u0020access\u0020token\u0020to\u0020TokenFilePath",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_SaveAccessToken"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ALoadAccessToken\u0028\u0029",
            "name": "LoadAccessToken",
            "summary": "Loads\u0020the\u0020access\u0020token\u0020from\u0020the\u0020file\u0020specified\u0020in\u0020TokenFilePath",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_LoadAccessToken"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ARefreshAccessToken\u0028\u0029",
            "name": "RefreshAccessToken",
            "summary": "Refresh\u0020the\u0020access\u0020token\u0020using\u0020the\u0020refresh\u0020token",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_RefreshAccessToken"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AGetOAuthProvider\u0028\u0029",
            "name": "GetOAuthProvider",
            "summary": "Creates\u0020a\u0020new\u0020instance\u0020of\u0020the\u0020OAuth2\u0020provider\u0020based\u0020on\u0020the\u0020configuration\u0020specified\u0020in\u0020the\u0020constructor",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_GetOAuthProvider"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ASendANAFRequest\u0028\u0029",
            "name": "SendANAFRequest",
            "summary": "All\u0020requests\u0020to\u0020ANAF\u0020are\u0020made\u0020through\u0020this\u0020method",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_SendANAFRequest"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ADoEntityFetch\u0028\u0029",
            "name": "DoEntityFetch",
            "summary": "Base\u0020method\u0020for\u0020fetching\u0020company\/institution\u0020data\u0020from\u0020ANAF",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_DoEntityFetch"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AUploadEFactura\u0028\u0029",
            "name": "UploadEFactura",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_UploadEFactura"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ADownloadAnswer\u0028\u0029",
            "name": "DownloadAnswer",
            "summary": "Download\u0020Answer\u0020from\u0020ANAF\nTo\u0020obtain\u0020the\u0020ID,\u0020use\u0020ListAnswers",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_DownloadAnswer"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AUBL2PDF\u0028\u0029",
            "name": "UBL2PDF",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_UBL2PDF"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ARemoveSchemaLocationAttribute\u0028\u0029",
            "name": "RemoveSchemaLocationAttribute",
            "summary": "Removes\u0020the\u0020xsi\u003AschemaLocation\u0020attribute\u0020from\u0020the\u0020root\u0020element\u0020of\u0020the\u0020UBL\u0020XML",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_RemoveSchemaLocationAttribute"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AListAnswers\u0028\u0029",
            "name": "ListAnswers",
            "summary": "Get\u0020answer\u0020list\u0020for\u0020a\u0020company\u0020\u0028authenticated\u0020user\u0020must\u0020have\u0020access\u0020to\u0020the\u0020company\u0021\u0029",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_ListAnswers"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AVerifyXML\u0028\u0029",
            "name": "VerifyXML",
            "summary": "ATTENTION\u0020DOES\u0020NOT\u0020FUNCTION\u0020RELIABLY.",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_VerifyXML"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ACallErrorCallback\u0028\u0029",
            "name": "CallErrorCallback",
            "summary": "Calls\u0020ErrorCallback\u0020with\u0020given\u0020params.",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_CallErrorCallback"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AHasAccessToken\u0028\u0029",
            "name": "HasAccessToken",
            "summary": "Check\u0020if\u0020the\u0020client\u0020has\u0020a\u0020valid\u0020access\u0020token.",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_HasAccessToken"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AIsProduction\u0028\u0029",
            "name": "IsProduction",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_IsProduction"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AValidateCIF\u0028\u0029",
            "name": "ValidateCIF",
            "summary": "Verifies\u0020a\u0020CUI\u0020given\u0020the\u0020official\u0020checksum\u0020algorithm",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#method_ValidateCIF"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003A\u0024Timeout",
            "name": "Timeout",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#property_Timeout"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003A\u0024Production",
            "name": "Production",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#property_Production"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003A\u0024AccessToken",
            "name": "AccessToken",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#property_AccessToken"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003A\u0024ErrorCallback",
            "name": "ErrorCallback",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#property_ErrorCallback"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003A\u0024OAuthConfig",
            "name": "OAuthConfig",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#property_OAuthConfig"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003A\u0024TokenFilePath",
            "name": "TokenFilePath",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFAPIClient.html#property_TokenFilePath"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address",
            "name": "Address",
            "summary": "Represents\u0020an\u0020address\u0020based\u0020on\u0020the\u0020ANAF\u0020API\u0020response\u0020structure",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003ACreateFromParsed\u0028\u0029",
            "name": "CreateFromParsed",
            "summary": "Similar\u0020to\u0020\u0040see\u0020Entity\u003A\u003ACreateFromParsed",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#method_CreateFromParsed"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003A\u0024denumire_Strada",
            "name": "denumire_Strada",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#property_denumire_Strada"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003A\u0024numar_Strada",
            "name": "numar_Strada",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#property_numar_Strada"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003A\u0024denumire_Localitate",
            "name": "denumire_Localitate",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#property_denumire_Localitate"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003A\u0024cod_Localitate",
            "name": "cod_Localitate",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#property_cod_Localitate"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003A\u0024denumire_Judet",
            "name": "denumire_Judet",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#property_denumire_Judet"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003A\u0024cod_Judet",
            "name": "cod_Judet",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#property_cod_Judet"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003A\u0024cod_JudetAuto",
            "name": "cod_JudetAuto",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#property_cod_JudetAuto"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003A\u0024tara",
            "name": "tara",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#property_tara"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003A\u0024detalii_Adresa",
            "name": "detalii_Adresa",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#property_detalii_Adresa"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Address\u003A\u003A\u0024cod_Postal",
            "name": "cod_Postal",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Address.html#property_cod_Postal"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Entity",
            "name": "Entity",
            "summary": "Represents\u0020the\u0020comprehensive\u0020response\u0020structure\u0020for\u0020a\u0020company\/institution\u0020from\u0020the\u0020ANAF\u0020API",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Entity.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Entity\u003A\u003ACreateFromParsed\u0028\u0029",
            "name": "CreateFromParsed",
            "summary": "Used\u0020to\u0020convert\u0020the\u0020parsed\u0020data\u0020\u0028json\u0029\u0020from\u0020the\u0020ANAF\u0020API\u0020to\u0020an\u0020Entity\u0020object",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Entity.html#method_CreateFromParsed"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Entity\u003A\u003AGetSector\u0028\u0029",
            "name": "GetSector",
            "summary": "Try\u0020to\u0020extract\u0020Bucharest\u0027s\u0020sector\u0020from\u0020the\u0020address\nWill\u0020return\u0020null\u0020if\u0020the\u0020address\u0020is\u0020not\u0020set\u0020or\u0020if\u0020the\u0020address\u0020does\u0020not\u0020contain\u0020a\u0020sector.",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Entity.html#method_GetSector"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Entity\u003A\u003A\u0024date_generale",
            "name": "date_generale",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Entity.html#property_date_generale"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Entity\u003A\u003A\u0024inregistrare_scop_Tva",
            "name": "inregistrare_scop_Tva",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Entity.html#property_inregistrare_scop_Tva"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Entity\u003A\u003A\u0024inregistrare_RTVAI",
            "name": "inregistrare_RTVAI",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Entity.html#property_inregistrare_RTVAI"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Entity\u003A\u003A\u0024stare_inactiv",
            "name": "stare_inactiv",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Entity.html#property_stare_inactiv"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Entity\u003A\u003A\u0024inregistrare_SplitTVA",
            "name": "inregistrare_SplitTVA",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Entity.html#property_inregistrare_SplitTVA"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Entity\u003A\u003A\u0024adresa_sediu_social",
            "name": "adresa_sediu_social",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Entity.html#property_adresa_sediu_social"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\Entity\u003A\u003A\u0024adresa_domiciliu_fiscal",
            "name": "adresa_domiciliu_fiscal",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-Entity.html#property_adresa_domiciliu_fiscal"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo",
            "name": "GeneralInfo",
            "summary": "Represents\u0020the\u0020general\u0020information\u0020about\u0020a\u0020company\u0020based\u0020on\u0020the\u0020ANAF\u0020API\u0020response\u0020structure",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003ACreateFromParsed\u0028\u0029",
            "name": "CreateFromParsed",
            "summary": "Similar\u0020to\u0020\u0040see\u0020Entity\u003A\u003ACreateFromParsed",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#method_CreateFromParsed"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024cui",
            "name": "cui",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_cui"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_data"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024denumire",
            "name": "denumire",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_denumire"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024adresa",
            "name": "adresa",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_adresa"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024nrRegCom",
            "name": "nrRegCom",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_nrRegCom"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024telefon",
            "name": "telefon",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_telefon"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024fax",
            "name": "fax",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_fax"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024codPostal",
            "name": "codPostal",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_codPostal"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024act",
            "name": "act",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_act"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024stare_inregistrare",
            "name": "stare_inregistrare",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_stare_inregistrare"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024cod_CAEN",
            "name": "cod_CAEN",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_cod_CAEN"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024iban",
            "name": "iban",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_iban"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024statusRO_e_Factura",
            "name": "statusRO_e_Factura",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_statusRO_e_Factura"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024organFiscalCompetent",
            "name": "organFiscalCompetent",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_organFiscalCompetent"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024forma_de_proprietate",
            "name": "forma_de_proprietate",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_forma_de_proprietate"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024forma_organizare",
            "name": "forma_organizare",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_forma_organizare"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\GeneralInfo\u003A\u003A\u0024forma_juridica",
            "name": "forma_juridica",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-GeneralInfo.html#property_forma_juridica"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\InactiveInfo",
            "name": "InactiveInfo",
            "summary": "Represents\u0020the\u0020inactive\u0020information\u0020about\u0020a\u0020company\u0020based\u0020on\u0020the\u0020ANAF\u0020API\u0020response\u0020structure",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-InactiveInfo.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\InactiveInfo\u003A\u003ACreateFromParsed\u0028\u0029",
            "name": "CreateFromParsed",
            "summary": "Similar\u0020to\u0020\u0040see\u0020Entity\u003A\u003ACreateFromParsed",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-InactiveInfo.html#method_CreateFromParsed"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\InactiveInfo\u003A\u003A\u0024dataInactivare",
            "name": "dataInactivare",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-InactiveInfo.html#property_dataInactivare"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\InactiveInfo\u003A\u003A\u0024dataReactivare",
            "name": "dataReactivare",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-InactiveInfo.html#property_dataReactivare"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\InactiveInfo\u003A\u003A\u0024dataPublicare",
            "name": "dataPublicare",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-InactiveInfo.html#property_dataPublicare"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\InactiveInfo\u003A\u003A\u0024dataRadiere",
            "name": "dataRadiere",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-InactiveInfo.html#property_dataRadiere"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\InactiveInfo\u003A\u003A\u0024statusInactivi",
            "name": "statusInactivi",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-InactiveInfo.html#property_statusInactivi"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\RTVAInfo",
            "name": "RTVAInfo",
            "summary": "Represents\u0020the\u0020RTVA\u0020\u0028taxable\u0020on\u0020payment\u003F\u0029\u0020\u0020information\u0020about\u0020a\u0020company\u0020based\u0020on\u0020the\u0020ANAF\u0020API\u0020response\u0020structure",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-RTVAInfo.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\RTVAInfo\u003A\u003ACreateFromParsed\u0028\u0029",
            "name": "CreateFromParsed",
            "summary": "Similar\u0020to\u0020\u0040see\u0020Entity\u003A\u003ACreateFromParsed",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-RTVAInfo.html#method_CreateFromParsed"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\RTVAInfo\u003A\u003A\u0024dataInceputTvaInc",
            "name": "dataInceputTvaInc",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-RTVAInfo.html#property_dataInceputTvaInc"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\RTVAInfo\u003A\u003A\u0024dataSfarsitTvaInc",
            "name": "dataSfarsitTvaInc",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-RTVAInfo.html#property_dataSfarsitTvaInc"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\RTVAInfo\u003A\u003A\u0024dataActualizareTvaInc",
            "name": "dataActualizareTvaInc",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-RTVAInfo.html#property_dataActualizareTvaInc"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\RTVAInfo\u003A\u003A\u0024dataPublicareTvaInc",
            "name": "dataPublicareTvaInc",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-RTVAInfo.html#property_dataPublicareTvaInc"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\RTVAInfo\u003A\u003A\u0024tipActTvaInc",
            "name": "tipActTvaInc",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-RTVAInfo.html#property_tipActTvaInc"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\RTVAInfo\u003A\u003A\u0024statusTvaIncasare",
            "name": "statusTvaIncasare",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-RTVAInfo.html#property_statusTvaIncasare"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\SplitTVAInfo",
            "name": "SplitTVAInfo",
            "summary": "Represents\u0020the\u0020split\u0020TVA\u0028broken\u0020down\u0020tax\u0020payment\u003F\u0029\u0020information\u0020about\u0020a\u0020company\u0020based\u0020on\u0020the\u0020ANAF\u0020API\u0020response\u0020structure",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-SplitTVAInfo.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\SplitTVAInfo\u003A\u003ACreateFromParsed\u0028\u0029",
            "name": "CreateFromParsed",
            "summary": "Similar\u0020to\u0020\u0040see\u0020Entity\u003A\u003ACreateFromParsed",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-SplitTVAInfo.html#method_CreateFromParsed"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\SplitTVAInfo\u003A\u003A\u0024dataInceputSplitTVA",
            "name": "dataInceputSplitTVA",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-SplitTVAInfo.html#property_dataInceputSplitTVA"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\SplitTVAInfo\u003A\u003A\u0024dataAnulareSplitTVA",
            "name": "dataAnulareSplitTVA",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-SplitTVAInfo.html#property_dataAnulareSplitTVA"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\SplitTVAInfo\u003A\u003A\u0024statusSplitTVA",
            "name": "statusSplitTVA",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-SplitTVAInfo.html#property_statusSplitTVA"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\TVAInfo",
            "name": "TVAInfo",
            "summary": "Represents\u0020the\u0020TVA\u0020information\u0020about\u0020a\u0020company\u0020based\u0020on\u0020the\u0020ANAF\u0020API\u0020response\u0020structure",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-TVAInfo.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\TVAInfo\u003A\u003ACreateFromParsed\u0028\u0029",
            "name": "CreateFromParsed",
            "summary": "Similar\u0020to\u0020\u0040see\u0020Entity\u003A\u003ACreateFromParsed",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-TVAInfo.html#method_CreateFromParsed"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\TVAInfo\u003A\u003A\u0024scpTVA",
            "name": "scpTVA",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-TVAInfo.html#property_scpTVA"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity\\TVAInfo\u003A\u003A\u0024perioade_TVA",
            "name": "perioade_TVA",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-ANAFEntity-TVAInfo.html#property_perioade_TVA"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswer",
            "name": "ANAFAnswer",
            "summary": "Represents\u0020answer\u0020structure\u0020for\u0020\u0040see\u0020ANAFAnswerListResponse\u003A\u003A\u0024mesaje",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswer.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswer\u003A\u003ACreateFromParsed\u0028\u0029",
            "name": "CreateFromParsed",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswer.html#method_CreateFromParsed"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswer\u003A\u003A\u0024data_creare",
            "name": "data_creare",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswer.html#property_data_creare"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswer\u003A\u003A\u0024cif",
            "name": "cif",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswer.html#property_cif"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswer\u003A\u003A\u0024id_solicitare",
            "name": "id_solicitare",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswer.html#property_id_solicitare"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswer\u003A\u003A\u0024detalii",
            "name": "detalii",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswer.html#property_detalii"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswer\u003A\u003A\u0024tip",
            "name": "tip",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswer.html#property_tip"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswer\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswer.html#property_id"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswerListResponse",
            "name": "ANAFAnswerListResponse",
            "summary": "Represents\u0020answer\u0020structure\u0020for\u0020\u0040see\u0020\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AListAnswers\u0028\u0029",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswerListResponse.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswerListResponse\u003A\u003ACreateFromParsed\u0028\u0029",
            "name": "CreateFromParsed",
            "summary": "Similar\u0020to\u0020\u0040see\u0020Entity\u003A\u003ACreateFromParsed",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswerListResponse.html#method_CreateFromParsed"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswerListResponse\u003A\u003ACreateError\u0028\u0029",
            "name": "CreateError",
            "summary": "Create\u0020an\u0020error\u0020response\nFor\u0020internal\u0020use\u0021",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswerListResponse.html#method_CreateError"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswerListResponse\u003A\u003A\u0024serial",
            "name": "serial",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswerListResponse.html#property_serial"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswerListResponse\u003A\u003A\u0024cui",
            "name": "cui",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswerListResponse.html#property_cui"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswerListResponse\u003A\u003A\u0024success",
            "name": "success",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswerListResponse.html#property_success"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswerListResponse\u003A\u003A\u0024titlu",
            "name": "titlu",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswerListResponse.html#property_titlu"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAnswerListResponse\u003A\u003A\u0024mesaje",
            "name": "mesaje",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAnswerListResponse.html#property_mesaje"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAPIResponse",
            "name": "ANAFAPIResponse",
            "summary": "Represents\u0020the\u0020base\u0020structure\u0020for\u0020some\u0020ANAF\u0020API\u0020responses",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAPIResponse.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAPIResponse\u003A\u003AParse\u0028\u0029",
            "name": "Parse",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAPIResponse.html#method_Parse"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAPIResponse\u003A\u003A\u0024success",
            "name": "success",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAPIResponse.html#property_success"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAPIResponse\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAPIResponse.html#property_message"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAPIResponse\u003A\u003A\u0024rawResspone",
            "name": "rawResspone",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAPIResponse.html#property_rawResspone"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFAPIResponse\u003A\u003A\u0024LastParseError",
            "name": "LastParseError",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFAPIResponse.html#property_LastParseError"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFVerifyResponse",
            "name": "ANAFVerifyResponse",
            "summary": "Represents\u0020the\u0020response\u0020structure\u0020for\u0020\u0040see\u0020\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AVerifyXML",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFVerifyResponse.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFVerifyResponse\u003A\u003AIsOK\u0028\u0029",
            "name": "IsOK",
            "summary": "Check\u0020if\u0020the\u0020response\u0020is\u0020OK",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFVerifyResponse.html#method_IsOK"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFVerifyResponse\u003A\u003ACreateFromParsed\u0028\u0029",
            "name": "CreateFromParsed",
            "summary": "Similar\u0020to\u0020\u0040see\u0020Entity\u003A\u003ACreateFromParsed",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFVerifyResponse.html#method_CreateFromParsed"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFVerifyResponse\u003A\u003A\u0024stare",
            "name": "stare",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFVerifyResponse.html#property_stare"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFVerifyResponse\u003A\u003A\u0024Messages",
            "name": "Messages",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFVerifyResponse.html#property_Messages"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\ANAFVerifyResponse\u003A\u003A\u0024trace_id",
            "name": "trace_id",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-ANAFVerifyResponse.html#property_trace_id"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\EntityResponse",
            "name": "EntityResponse",
            "summary": "Represents\u0020the\u0020response\u0020structure\u0020for\u0020\u0040see\u0020\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AGetEntity",
            "url": "classes/EdituraEDU-ANAF-Responses-EntityResponse.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\EntityResponse\u003A\u003AParse\u0028\u0029",
            "name": "Parse",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-EntityResponse.html#method_Parse"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\EntityResponse\u003A\u003A\u0024Entity",
            "name": "Entity",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-EntityResponse.html#property_Entity"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\TVAResponse",
            "name": "TVAResponse",
            "summary": "Represents\u0020the\u0020response\u0020structure\u0020for\u0020\u0040see\u0020\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003ACheckTVAStatus\u0028\u0029",
            "url": "classes/EdituraEDU-ANAF-Responses-TVAResponse.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\TVAResponse\u003A\u003AParse\u0028\u0029",
            "name": "Parse",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-TVAResponse.html#method_Parse"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\TVAResponse\u003A\u003A\u0024IsTVARegistered",
            "name": "IsTVARegistered",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-TVAResponse.html#property_IsTVARegistered"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\UBLUploadResponse",
            "name": "UBLUploadResponse",
            "summary": "Represents\u0020the\u0020response\u0020structure\u0020for\u0020\u0040see\u0020\\EdituraEDU\\ANAF\\ANAFAPIClient\u003A\u003AUploadEFactura\u0028\u0029",
            "url": "classes/EdituraEDU-ANAF-Responses-UBLUploadResponse.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\UBLUploadResponse\u003A\u003AParse\u0028\u0029",
            "name": "Parse",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-UBLUploadResponse.html#method_Parse"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\UBLUploadResponse\u003A\u003AisJson\u0028\u0029",
            "name": "isJson",
            "summary": "Used\u0020to\u0020check\u0020if\u0020API\u0020response\u0020is\u0020JSON\nAnswers\u0020that\u0020are\u0020JSON\u0020are\u0020errors",
            "url": "classes/EdituraEDU-ANAF-Responses-UBLUploadResponse.html#method_isJson"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\UBLUploadResponse\u003A\u003AisErrorResponse\u0028\u0029",
            "name": "isErrorResponse",
            "summary": "Used\u0020to\u0020check\u0020if\u0020API\u0020response\u0020is\u0020a\u0020specific\u0020type\u0020of\u0020error.\u0020Can\u0020be\u0020indicative\u0020of\u0020a\u0020bad\u0020request\/invalid\u0020input\u0020data",
            "url": "classes/EdituraEDU-ANAF-Responses-UBLUploadResponse.html#method_isErrorResponse"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\UBLUploadResponse\u003A\u003AparseXML\u0028\u0029",
            "name": "parseXML",
            "summary": "Parse\u0020response\u0020XML",
            "url": "classes/EdituraEDU-ANAF-Responses-UBLUploadResponse.html#method_parseXML"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\UBLUploadResponse\u003A\u003AparseJSON\u0028\u0029",
            "name": "parseJSON",
            "summary": "Parse\u0020JSON\u0020error",
            "url": "classes/EdituraEDU-ANAF-Responses-UBLUploadResponse.html#method_parseJSON"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\UBLUploadResponse\u003A\u003AconvertToTimestamp\u0028\u0029",
            "name": "convertToTimestamp",
            "summary": "Convert\u0020date\u0020string\u0020to\u0020timestamp",
            "url": "classes/EdituraEDU-ANAF-Responses-UBLUploadResponse.html#method_convertToTimestamp"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses\\UBLUploadResponse\u003A\u003A\u0024ResponseTimestamp",
            "name": "ResponseTimestamp",
            "summary": "",
            "url": "classes/EdituraEDU-ANAF-Responses-UBLUploadResponse.html#property_ResponseTimestamp"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF",
            "name": "ANAF",
            "summary": "",
            "url": "namespaces/edituraedu-anaf.html"
        },                {
            "fqsen": "\\EdituraEDU",
            "name": "EdituraEDU",
            "summary": "",
            "url": "namespaces/edituraedu.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\ANAFEntity",
            "name": "ANAFEntity",
            "summary": "",
            "url": "namespaces/edituraedu-anaf-anafentity.html"
        },                {
            "fqsen": "\\EdituraEDU\\ANAF\\Responses",
            "name": "Responses",
            "summary": "",
            "url": "namespaces/edituraedu-anaf-responses.html"
        }            ]
);
